package byetube

// Lists copied from the router ByeTube payload (/usr/share/bytetube/*).
var defaultDomains = []string{
	"android.clients.google.com",
	"beacons.gvt2.com",
	"cdn.youtube.com",
	"connectivitycheck.gstatic.com",
	"fonts.googleapis.com",
	"fonts.gstatic.com",
	"ggpht.com",
	"googleapis.com",
	"googleplay.com",
	"googleusercontent.com",
	"googlevideo.com",
	"gvt1.com",
	"i.ytimg.com",
	"i9.ytimg.com",
	"jnn-pa.googleapis.com",
	"kids.youtube.com",
	"lh3.googleusercontent.com",
	"m.youtube.com",
	"manifest.googlevideo.com",
	"music.youtube.com",
	"nhacmp3youtube.com",
	"play-fe.googleapis.com",
	"play-games.googleusercontent.com",
	"play-lh.googleusercontent.com",
	"play.google.com",
	"play.googleapis.com",
	"prod-lt-playstoregatewayadapter-pa.googleapis.com",
	"returnyoutubedislikeapi.com",
	"s.ytimg.com",
	"signaler-pa.youtube.com",
	"studio.youtube.com",
	"tv.youtube.com",
	"wide-youtube.l.google.com",
	"withyoutube.com",
	"youtu.be",
	"youtube-nocookie.com",
	"youtube-ui.l.google.com",
	"youtube.ae",
	"youtube.al",
	"youtube.am",
	"youtube.at",
	"youtube.az",
	"youtube.ba",
	"youtube.be",
	"youtube.bg",
	"youtube.bh",
	"youtube.bo",
	"youtube.by",
	"youtube.ca",
	"youtube.cat",
	"youtube.ch",
	"youtube.cl",
	"youtube.co",
	"youtube.co.ae",
	"youtube.co.at",
	"youtube.co.cr",
	"youtube.co.hu",
	"youtube.co.id",
	"youtube.co.il",
	"youtube.co.in",
	"youtube.co.jp",
	"youtube.co.ke",
	"youtube.co.kr",
	"youtube.co.ma",
	"youtube.co.nz",
	"youtube.co.th",
	"youtube.co.tz",
	"youtube.co.ug",
	"youtube.co.uk",
	"youtube.co.ve",
	"youtube.co.za",
	"youtube.co.zw",
	"youtube.com",
	"youtube.com.ar",
	"youtube.com.au",
	"youtube.com.az",
	"youtube.com.bd",
	"youtube.com.bh",
	"youtube.com.bo",
	"youtube.com.br",
	"youtube.com.by",
	"youtube.com.co",
	"youtube.com.do",
	"youtube.com.ec",
	"youtube.com.ee",
	"youtube.com.eg",
	"youtube.com.es",
	"youtube.com.gh",
	"youtube.com.gr",
	"youtube.com.gt",
	"youtube.com.hk",
	"youtube.com.hn",
	"youtube.com.hr",
	"youtube.com.jm",
	"youtube.com.jo",
	"youtube.com.kw",
	"youtube.com.lb",
	"youtube.com.lv",
	"youtube.com.ly",
	"youtube.com.mk",
	"youtube.com.mt",
	"youtube.com.mx",
	"youtube.com.my",
	"youtube.com.ng",
	"youtube.com.ni",
	"youtube.com.om",
	"youtube.com.pa",
	"youtube.com.pe",
	"youtube.com.ph",
	"youtube.com.pk",
	"youtube.com.pt",
	"youtube.com.py",
	"youtube.com.qa",
	"youtube.com.ro",
	"youtube.com.sa",
	"youtube.com.sg",
	"youtube.com.sv",
	"youtube.com.tn",
	"youtube.com.tr",
	"youtube.com.tw",
	"youtube.com.ua",
	"youtube.com.uy",
	"youtube.com.ve",
	"youtube.cr",
	"youtube.cz",
	"youtube.de",
	"youtube.dk",
	"youtube.ee",
	"youtube.es",
	"youtube.fi",
	"youtube.fr",
	"youtube.ge",
	"youtube.googleapis.com",
	"youtube.gr",
	"youtube.gt",
	"youtube.hk",
	"youtube.hr",
	"youtube.hu",
	"youtube.ie",
	"youtube.in",
	"youtube.iq",
	"youtube.is",
	"youtube.it",
	"youtube.jo",
	"youtube.jp",
	"youtube.kr",
	"youtube.kz",
	"youtube.la",
	"youtube.lk",
	"youtube.lt",
	"youtube.lu",
	"youtube.lv",
	"youtube.ly",
	"youtube.ma",
	"youtube.md",
	"youtube.me",
	"youtube.mk",
	"youtube.mn",
	"youtube.mx",
	"youtube.my",
	"youtube.ng",
	"youtube.ni",
	"youtube.nl",
	"youtube.no",
	"youtube.pa",
	"youtube.pe",
	"youtube.ph",
	"youtube.pk",
	"youtube.pl",
	"youtube.pr",
	"youtube.pt",
	"youtube.qa",
	"youtube.ro",
	"youtube.rs",
	"youtube.ru",
	"youtube.sa",
	"youtube.se",
	"youtube.sg",
	"youtube.si",
	"youtube.sk",
	"youtube.sn",
	"youtube.soy",
	"youtube.sv",
	"youtube.tn",
	"youtube.tv",
	"youtube.ua",
	"youtube.ug",
	"youtube.uy",
	"youtube.vn",
	"youtubeeducation.com",
	"youtubeembeddedplayer.googleapis.com",
	"youtubefanfest.com",
	"youtubegaming.com",
	"youtubego.co.id",
	"youtubego.co.in",
	"youtubego.com",
	"youtubego.com.br",
	"youtubego.id",
	"youtubego.in",
	"youtubei.googleapis.com",
	"youtubei.youtube.com",
	"youtubekids.com",
	"youtubemobilesupport.com",
	"yt-video-upload.l.google.com",
	"yt.be",
	"yt3.ggpht.com",
	"yt3.googleusercontent.com",
	"yt4.ggpht.com",
	"ytimg.com",
	"ytimg.l.google.com",
	"yting.com",
}

var testStrategies = []string{
	"-f-200 -Qr -s3:5+sm -a1 -As -d1 -s4+sm -s8+sh -f-300 -d6+sh -a1 -At,r,s -o2 -f-30 -As -r5 -Mh -r6+sh -f-250 -s2:7+s -s3:6+sm -a1 -At,r,s -s3:5+sm -s6+s -s7:9+s -q30+sm -a1",
	"-d1 -d3+s -s6+s -d9+s -s12+s -d15+s -s20+s -d25+s -s30+s -d35+s -r1+s -S -a1 -As -d1 -d3+s -s6+s -d9+s -s12+s -d15+s -s20+s -d25+s -s30+s -d35+s -S -a1",
	"-q2 -s2 -s3+s -r3 -s4 -r4 -s5+s -r5+s -s6 -s7+s -r8 -s9+s -Qr -Mh,d,r -a1 -At,r -s2+s -r2 -d2 -s3 -r3 -r4 -s4 -d5+s -r5 -d6 -s7+s -d7 -a1",
	"-o1 -d1 -a1 -At,r,s -s1 -d1 -s5+s -s10+s -s15+s -s20+s -r1+s -S -a1 -As -s1 -d1 -s5+s -s10+s -s15+s -s20+s -S -a1",
	"-n \"google.com\" -Qr -f-204 -s1:5+sm -a1 -As -d1 -s3+s -s5+s -q7 -a1 -As -o2 -f-43 -a1 -As -r5 -Mh -s1:5+s -s3:7+sm -a1",
	"-n \"google.com\" -Qr -f-205 -a1 -As -s1:3+sm -a1 -As -s5:8+sm -a1 -As -d3 -q7 -o2 -f-43 -f-85 -f-165 -r5 -Mh -a1",
	"-d1+s -s50+s -a1 -As -f20 -r2+s -a1 -At -d2 -s1+s -s5+s -s10+s -s15+s -s25+s -s35+s -s50+s -s60+s -a1",
	"-o1 -a1 -At,r,s -f-1 -a1 -At,r,s -d1:11+sm -S -a1 -At,r,s -n \"google.com\" -Qr -f1 -d1:11+sm -s1:11+sm -S -a1",
	"-d1 -s1 -q1 -a1 -Ar -s5 -o1+s -d3+s -s6+s -d9+s -s12+s -d15+s -s20+s -d25+s -s30+s -d35+s -a1",
	"-f1+nme -t6 -a1 -As -n \"google.com\" -Qr -s1:6+sm -a1 -As -s5:12+sm -a1 -As -d3 -q7 -r6 -Mh -a1",
	"-d1 -s1+s -d3+s -s6+s -d9+s -s12+s -d15+s -s20+s -d25+s -s30+s -d35+s -a1",
	"-d1 -s1+s -d1+s -s3+s -d6+s -s12+s -d14+s -s20+s -d24+s -s30+s -a1",
	"-o1 -a1 -At,r,s -f-1 -a1 -Ar,s -o1 -a1 -At -r1+s -f-1 -t6 -a1",
	"-d1 -s1+s -s3+s -s6+s -s9+s -s12+s -s15+s -s20+s -s30+s -a1",
	"-d1 -d3+s -s6+s -d6+s -s7+s -d8+s -s10+s -a1 -t12 -At,s -r3",
	"-f1 -t5 -n \"google.com\" -q3+h -Qr -f2 -q1 -r1+s -t15 -q1 -o2 -a1",
	"-n \"google.com\" -d2:5:2+h -f-3 -r2+sm -o2 -o50+s -r2+s -f-4 -a1",
	"-f-1 -Qr -s1+sm -d3+s -s5+sm -o2 -a1 -As -r1+s -d8+s -a1",
	"-r-1+s -o20+sm -s3:7+sm -d5:3+sm -f300+s -Qr -f-1 -a1",
	"-o2 -O4 -s1 -q1 -a1 -Ar -s5 -o1+s -f1+s -r20+s -a1",
	"-o1 -r-5+se -a1 -At,r,s -d1 -n \"google.com\" -Qr -f-1 -a1",
	"--fake -1 --ttl 8 --split 1+s --disorder 3+s -a1",
	"-n \"google.com\" -Qr -f6+nr -d2 -d11 -f9+hm -o3 -t7 -a1",
	"-r5+s -s25+s -a1 -At,r,s -s50 -r5+s -s50+s -a1",
	"-d1 -d3+s -s6+s -d9+s -s20+s -d25+s -s30+s -a1",
	"-d9+s -q20+s -s25+s -t5 -a1 -At,r,s -r1+h -a1",
	"-q1+s -s29+s -s30+s -s14+s -o5+s -f-1 -S -a1",
	"-d1 -s1+s -r1+s -e1 -m1 -o1+s -f-1 -t2 -a1",
	"-d1 -o1 -a1 -Ar -o1 -a1 -At -f-1 -r1+s -a1",
	"-d1 -s4 -d8 -s1+s -d5+s -s10+s -d20+s -a1",
	"-f-1 -n \"google.com\" -Qr -s2+s -r3 -o20 -t4 -a1",
	"-n \"google.com\" -Qr -d5+sm -f3+sm -o2 -t4 -a1",
	"-o1 -a1 -Ar -q1 -a1 -At -f-1 -r1+s -a1",
	"-q1 -a1 -Ar -o1 -a1 -At -f-1 -r1+s -a1",
	"-s4+sn -r9+s -Qr -n \"google.com\" -S -a1",
	"-o1 -d1 -r1+s -S -s1+s -d3+s -a1",
	"-q1+s -s29+s -o5+s -f-1 -S -a1",
	"-n \"google.com\" -Qr -m2 -f-1 -d7 -a1",
	"-d1 -s1+s -r1+s -f-1 -t8 -a1",
	"-o1 -a1 -An -f1+nme -t6 -a1",
	"-n \"google.com\" -Qr -f-1 -r1+s -a1",
	"-n \"google.com\" -Qr -d1:3 -f-1 -a1",
	"-s1 -d3+s -a1 -At -r1+s -a1",
	"-f-1 -t8 -n \"google.com\" -s1+s -a1",
	"-n \"google.com\" -Qr -d1 -f-1 -a1",
	"-f64+se -n \"google.com\" -t5 -a1",
	"-o1 -a1 -At,r,s -d1 -a1",
	"-d1+s -o2 -s5 -r5 -a1",
	"-r8 -o2 -s7 -q4+s -a1",
	"-o1 -f-1 -r-5+se -a1",
	"-d6+s -q4+hm -o2 -a1",
	"-s5+s -s35+s -m4 -a1",
	"-f-1+sm -t7 -m2 -a1",
	"-o1 -r-5+se -a1",
	"-o1+s -d3+s -a1",
	"-o1 -s4 -s6 -a1",
	"-q1 -r25+s -a1",
	"-d1 -s3+s -a1",
	"-o3 -d7 -a1",
	"-d7 -s2 -a1",
	"-o1 -a1 -r-5+se",
}

var testDomains = []string{
	"youtu.be",
	"youtube.com",
	"i.ytimg.com",
	"i9.ytimg.com",
	"yt3.ggpht.com",
	"yt4.ggpht.com",
	"googleapis.com",
	"jnn-pa.googleapis.com",
	"googleusercontent.com",
	"signaler-pa.youtube.com",
	"youtubei.googleapis.com",
	"manifest.googlevideo.com",
	"yt3.googleusercontent.com",
	"rr1---sn-4axm-n8vs.googlevideo.com",
	"rr1---sn-gvnuxaxjvh-o8ge.googlevideo.com",
	"rr1---sn-ug5onuxaxjvh-p3ul.googlevideo.com",
	"rr1---sn-ug5onuxaxjvh-n8v6.googlevideo.com",
	"rr4---sn-q4flrnsl.googlevideo.com",
	"rr10---sn-gvnuxaxjvh-304z.googlevideo.com",
	"rr14---sn-n8v7kn7r.googlevideo.com",
	"rr16---sn-axq7sn76.googlevideo.com",
	"rr1---sn-8ph2xajvh-5xge.googlevideo.com",
	"rr1---sn-gvnuxaxjvh-5gie.googlevideo.com",
	"rr12---sn-gvnuxaxjvh-bvwz.googlevideo.com",
	"rr5---sn-n8v7knez.googlevideo.com",
	"rr1---sn-u5uuxaxjvhg0-ocje.googlevideo.com",
	"rr2---sn-q4fl6ndl.googlevideo.com",
	"rr5---sn-gvnuxaxjvh-n8vk.googlevideo.com",
	"rr4---sn-jvhnu5g-c35d.googlevideo.com",
	"rr1---sn-q4fl6n6y.googlevideo.com",
	"rr2---sn-hgn7ynek.googlevideo.com",
	"rr1---sn-xguxaxjvh-gufl.googlevideo.com",
}
